language: java
deploy:
  provider: releases
  api_key:
    secure: 30zEQCv3gPbsnEb5cJg+jQf8/kUSmmmDmZOYvbxNsFSKoevaoLlhZnNXiQcpDhGYwMm8FV9oKprnAJWGz1xwnnC8xmJVjvKuZZVaTtXkNBm6CnxCiXPqWm5SAyLXKxGEdaUe0opJOhVbXHCKeeERZJQcclXL6z8CWWUSkmgryKlOqL9eqeV9+OoAgdqPH+LtbIzt/uL6WRXk49Y1y6n2JQI75Hwef3ODn/6Md9T7jIAe8WCVYDn7GUOTqBlpceJs+iI2Fd890zawpM6qJypwAvAV1vUSPrKRYk7eE8kLDMStM7l3gzpwMxYxhRyD64H3xLM4kvsXI+dJLs00V6DUt8PK08b3vyKSGzF+a4WsmSvcBiIhJ2U4p0n33/sd8yF8Q3adKcoWvQFsh3ByFigIKgvUEnkDERPw/ViBQpt7UGp7S3CQLpbO+djMqmNTMxNtQSqWHmG5Ht9EedW39ac+vDgIZjOKy0JXlVc+X8JfKDfKI/4eSzbLHjrwBl1BT49r8y+kX/22q9DcgTs4S6G+DbdAzVLpd7KQvMhCDoCwI6NAqfUpWsML+IU64nTFTwBLUj9io+u2jJWE+vqM3t6Ww7EA29wC51uzlXvg1hUpmPV4qBkV9wXi37wHFnpcMW6xKANcJ0h5mN/XvP4m+t/hdlLsyJrPzcIV1DMVjcDZMs0=
  file_glob: true
  file: build/libs/xlr_tosca-plugin*.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-tosca-plugin
